package fpuna.py.com.appolympos.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CIUDADES".
 */
public class Ciudades {

    private Long id;
    private String descripcion;
    private Long idDepartamento;

    public Ciudades() {
    }

    public Ciudades(Long id) {
        this.id = id;
    }

    public Ciudades(Long id, String descripcion, Long idDepartamento) {
        this.id = id;
        this.descripcion = descripcion;
        this.idDepartamento = idDepartamento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getIdDepartamento() {
        return idDepartamento;
    }

    public void setIdDepartamento(Long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

}
