package fpuna.py.com.appolympos.entities;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ClientesDao.createTable(db, ifNotExists);
        CircuitosDao.createTable(db, ifNotExists);
        DepartamentosDao.createTable(db, ifNotExists);
        CiudadesDao.createTable(db, ifNotExists);
        VendedoresDao.createTable(db, ifNotExists);
        ProductosDao.createTable(db, ifNotExists);
        NoCompraDao.createTable(db, ifNotExists);
        TransactionsDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ClientesDao.dropTable(db, ifExists);
        CircuitosDao.dropTable(db, ifExists);
        DepartamentosDao.dropTable(db, ifExists);
        CiudadesDao.dropTable(db, ifExists);
        VendedoresDao.dropTable(db, ifExists);
        ProductosDao.dropTable(db, ifExists);
        NoCompraDao.dropTable(db, ifExists);
        TransactionsDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ClientesDao.class);
        registerDaoClass(CircuitosDao.class);
        registerDaoClass(DepartamentosDao.class);
        registerDaoClass(CiudadesDao.class);
        registerDaoClass(VendedoresDao.class);
        registerDaoClass(ProductosDao.class);
        registerDaoClass(NoCompraDao.class);
        registerDaoClass(TransactionsDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
