package fpuna.py.com.appolympos.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRODUCTOS".
 */
public class Productos {

    private Long id;
    private String descripcion;
    private String codigoBarra;
    private Double precioVenta;
    private Double cantidad;
    private Boolean tieneFoto;
    private String foto;

    public Productos() {
    }

    public Productos(Long id) {
        this.id = id;
    }

    public Productos(Long id, String descripcion, String codigoBarra, Double precioVenta, Double cantidad, Boolean tieneFoto, String foto) {
        this.id = id;
        this.descripcion = descripcion;
        this.codigoBarra = codigoBarra;
        this.precioVenta = precioVenta;
        this.cantidad = cantidad;
        this.tieneFoto = tieneFoto;
        this.foto = foto;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getCodigoBarra() {
        return codigoBarra;
    }

    public void setCodigoBarra(String codigoBarra) {
        this.codigoBarra = codigoBarra;
    }

    public Double getPrecioVenta() {
        return precioVenta;
    }

    public void setPrecioVenta(Double precioVenta) {
        this.precioVenta = precioVenta;
    }

    public Double getCantidad() {
        return cantidad;
    }

    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }

    public Boolean getTieneFoto() {
        return tieneFoto;
    }

    public void setTieneFoto(Boolean tieneFoto) {
        this.tieneFoto = tieneFoto;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

}
