package fpuna.py.com.appolympos.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRANSACTIONS".
 */
public class Transactions {

    private Long id;
    private String type;
    private String ClientId;
    private String ClientName;
    private Integer amount;
    private String httpDetail;
    private Integer status;
    private Integer attempts;
    private java.util.Date createdAt;
    private java.util.Date updatedAt;
    private String observation;
    private Integer queued;
    private Integer tries;

    public Transactions() {
    }

    public Transactions(Long id) {
        this.id = id;
    }

    public Transactions(Long id, String type, String ClientId, String ClientName, Integer amount, String httpDetail, Integer status, Integer attempts, java.util.Date createdAt, java.util.Date updatedAt, String observation, Integer queued, Integer tries) {
        this.id = id;
        this.type = type;
        this.ClientId = ClientId;
        this.ClientName = ClientName;
        this.amount = amount;
        this.httpDetail = httpDetail;
        this.status = status;
        this.attempts = attempts;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.observation = observation;
        this.queued = queued;
        this.tries = tries;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getClientId() {
        return ClientId;
    }

    public void setClientId(String ClientId) {
        this.ClientId = ClientId;
    }

    public String getClientName() {
        return ClientName;
    }

    public void setClientName(String ClientName) {
        this.ClientName = ClientName;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public String getHttpDetail() {
        return httpDetail;
    }

    public void setHttpDetail(String httpDetail) {
        this.httpDetail = httpDetail;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getAttempts() {
        return attempts;
    }

    public void setAttempts(Integer attempts) {
        this.attempts = attempts;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getObservation() {
        return observation;
    }

    public void setObservation(String observation) {
        this.observation = observation;
    }

    public Integer getQueued() {
        return queued;
    }

    public void setQueued(Integer queued) {
        this.queued = queued;
    }

    public Integer getTries() {
        return tries;
    }

    public void setTries(Integer tries) {
        this.tries = tries;
    }

}
